# Generated by Django 5.2.7 on 2025-10-28 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_rename_update_at_user_updated_at'),
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelSetting',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=150)),
                ('temperature_min', models.FloatField()),
                ('temperature_max', models.FloatField()),
                ('humidity_min', models.IntegerField(blank=True, null=True)),
                ('humidity_max', models.IntegerField(blank=True, null=True)),
                (
                    'weather_condition',
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ('category_combo', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutfitRecommendation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('rec_1', models.CharField(max_length=255)),
                ('rec_2', models.CharField(blank=True, max_length=255, null=True)),
                ('rec_3', models.CharField(blank=True, max_length=255, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'model_setting',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='recommend.aimodelsetting',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='users.user'
                    ),
                ),
                (
                    'weather_data',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='weather.weatherdata',
                    ),
                ),
            ],
        ),
    ]
