# Generated by Django 5.2.7 on 2025-10-28 06:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='AiChatlog',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('user_id', models.IntegerField()),
                ('session_id', models.CharField(db_index=True, max_length=200)),
                ('user_question', models.TextField()),
                ('ai_answer', models.TextField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, null=True)),
                (
                    'created_at',
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                'db_table': 'ai_chat_logs',
                'indexes': [
                    models.Index(fields=['session_id', 'created_at'], name='ai_logs')
                ],
            },
        ),
    ]
